# Generated by Django 5.0.1 on 2024-01-29 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
